<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
    <header>
        <nav>
            <div class="logo">
                <a href="/Index/"><img src="/images/moreplaylist.png" alt="More Playlist"></a>
            </div>
            <ul>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container">
            <h1>Logged out.</h1>
            <p>Thank you for using this site.</p>
            <a href="/Index" class="button">Home</a>
        </div>
    </main>
    <footer>
        <p>c 2016 More Playlist</p>
    </footer>
</body>
</html>
